# Generated by Django 4.2 on 2024-11-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='my_slug', unique=True),
            preserve_default=False,
        ),
    ]
