# Generated by Django 4.2 on 2024-11-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
