# Generated by Django 4.2 on 2024-11-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazins', '0002_revista_alter_publicatie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='publicatie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='magazins.publicatie'),
            preserve_default=False,
        ),
    ]
